# Generated by Django 4.2.8 on 2024-08-08 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("khsetra", "0001_initial"),
        ("core", "0003_remove_khsetra_mandir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandal",
            name="khestra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="khsetra.khsetra",
            ),
        ),
        migrations.DeleteModel(
            name="Khsetra",
        ),
    ]
