# Generated by Django 4.2.8 on 2024-08-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_mandal_khestra_delete_khsetra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mandal",
            name="khestra",
        ),
    ]
