# Generated by Django 4.2.8 on 2024-08-02 18:17

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mandir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "Active"), (1, "Deleted")],
                        default=0,
                        null=True,
                        verbose_name="The life cycle status of this object",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Name of Mandir",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="City of Mandir",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
