# Generated by Django 4.2.8 on 2024-08-14 17:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("khsetra", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "Active"), (1, "Deleted")],
                        default=0,
                        null=True,
                        verbose_name="The life cycle status of this object",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Mandal",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="mandal.basemodel",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Name of Mandal",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Unique number of Mandal",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Bal", "Bal"),
                            ("Balika", "Balika"),
                            ("Yuvak", "Yuvak"),
                            ("Yuvati", "Yuvati"),
                            ("Sanyukt", "Sanyukt"),
                            ("Mahila", "Mahila"),
                        ],
                        max_length=16,
                        verbose_name="Mandal type",
                    ),
                ),
                (
                    "sanchaalak_name",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Name of Mandal Sanchalak",
                    ),
                ),
                (
                    "sanchaalak_contact_number",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="Contact number of Mandal Sanchalak",
                    ),
                ),
                (
                    "nirikshak_name",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Name of Nirikshak",
                    ),
                ),
                (
                    "nirikshak_contact_number",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="Contact number of Nirikshak",
                    ),
                ),
                (
                    "khestra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="khsetra.khsetra",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
            bases=("mandal.basemodel",),
        ),
    ]
